name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/Setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run script
        run: |
          python app.py

      - name: Deploy to Tencent Cloud CVM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CVM_IP_ADDRESS }}
          username: ${{ secrets.CVM_USERNAME }}
          password: ${{ secrets.CVM_PASSWORD }}
          script: |
            # 进入目标目录（如果不存在，则创建）
            mkdir -p ~/HHM
            cd ~/HHM

            # 如果仓库未克隆，则执行 git clone，否则执行 git pull
            if [ ! -d "./Lab1-ci-cd/.git" ]; then
              echo "Cloning repository..."
              git clone https://github.com/He0922/Lab1-ci-cd.git ||exit 1
            else
              echo "Repository exists, pulling latest changes..."
              cd Lab1-ci-cd
              git reset --hard  # 防止本地修改导致 pull 失败
              git pull origin main || exit 1
            fi